server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

clients:
  users:
    name: restaurants
    base-url: http://localhost:9091/api/v1/restaurants

security:
  jwt:
    secret: "Rk9yNk5tQ0trdnhWc1N4blBQYnlzMHRFVmV6M2hHR3g"
    expiration: 3600000

appDescription: "Pragma Usuarios"
appVersion: "1.0.0"